# Generated by Django 5.0 on 2023-12-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='explanation',
            new_name='topic',
        ),
    ]
